name: Check Website

# 스케줄 설정: 30분마다
on:
  schedule:
    - cron: "*/5 * * * *"    
  workflow_dispatch:          # 수동 실행 가능

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 코드 체크아웃
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Python 설치
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️⃣ 의존성 설치
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      # 4️⃣ 스크립트 실행
      - name: Run chk website
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python chk_website.py









